### ISSUE TITLE
Board Pins

### ISSUE THREAD

**Issue by milicigoran** [PaulGD03/Bear-Duet-Klipper#1]
How do i know what pins are what? i'm looking at he pins file and it says tha the probe_pin is PD0 and looking at the duet board there isnt such a pin. All the pins look like they have style like they are from a Bigtreetech motherboard and not a duet board. so is there a way to figure out what pins means what on the duet?

**Comment by milicigoran** [comment]
nevermind found the page. for some reason it wasnt in my folder i downloaded but it was on github

**Comment by PaulGD03** [comment]
Hey there, I just updated the repo to fix a few things and make it work properly.
